### ISSUE TITLE
Error and Traceback given when starting capsid from the Command Promt

### ISSUE THREAD

**Issue by MediQ-Itay** [capsid/capsid#45]
After sending the command 'capsid' the the consoe outputs the following:
root@terminal:/home/user/Downloads# capsid
    Traceback (most recent call last):
      File "/usr/local/bin/capsid", line 13, in <module>
        import capsid
      File "/usr/local/lib/python2.7/dist-packages/capsid/**init**.py", line 15, in <module>
        import configure, qfilter, gbloader, subtraction, statistics, fasta, intersect, project, sample, alignment, taxonomy
      File "/usr/local/lib/python2.7/dist-packages/capsid/configure.py", line 20, in <module>
        from database import *
      File "/usr/local/lib/python2.7/dist-packages/capsid/database.py", line 14, in <module>
       from pymongo import Connection
    ImportError: cannot import name Connection

**Comment by morungos** [comment]
I'm guessing this is because of: https://github.com/MITRECND/WhoDat/issues/7, i.e., the pymongo. Connection API has now been removed. You might be able to downgrade to an older pymongo (pre- pymongo 3.0.2), or @iborozan'll have to fix the DB connection.

**Comment by iborozan** [comment]
The setup script now enforces the use of pymongo version==2.8 (please see the latest setup.py
 in the master branch). This should prevent the pymongo error above.
